# cd aliases
alias @cddown="cd ~/Downloads"
alias @cddoc="cd ~/Documents"
alias @cdcode="cd ~/Code"
alias @cdh="cd ~"

# tool aliases
alias @rmr="rm -rvfI"
alias @histgrep="history | grep"
alias @psgrep="ps aux | grep"

# tmux
alias @tmux-new="tmux new -s"
alias @tmux-attach="tmux a -t"
alias @tmux-kill="tmux kill-session -t"
alias @tmux-ls="tmux ls"

# docker
alias @docker-deploy="ansible-playbook <path>/all-images.yml -t"
alias @docker-exec-ti="docker exec -ti"

# network
alias @net-dnslookup="dig +short -x"
alias @net-whois="whois -H"
alias @net-connections="watch netstat -tupnWo"
alias @net-listens="netstat -tulpnWo"

# usefuls - uncomment before using
# alias @backup-file='echo "Started at: `date +%FT%H:%M:%S.%N`" && rsync -avh --progress --stats --log-file=/tmp/rsync.log <src_dir> <dst_dir> && echo "Ended at: `date +%FT%H:%M:%S.%N`"'
# alias @mount-vol='sudo mount -t cifs //<host_name>/<vol_name> /mnt/<host_name>/<vol_name> -o user=<login_username>,gid=<grp_name>,uid=<owner_name>'
