---
- name: debian development tools
  hosts: local
  sudo: yes
  #remote_user:
  
 vars_prompt:
    - name: "overwrite_git_files"
      prompt: "Overwrite ~/.git* files (yes or ENTER to skip)?"
      private: no
           
  roles:
    - deb-devel-tools
