- name: mysql
  tags:
    - mysql
  docker:
    name: mysql
    image: mysql:latest
    state: started
    net: host
    volumes:
      - "/opt/docker-volumes/mysql:/var/lib/mysql"
    env:
        MYSQL_ROOT_PASSWORD: root