---
- name: install vim
  apt: pkg=vim state=installed

- name: add .vimrc
  copy: src=vim/vim.vimrc dest=/home/{{ ansible_env.SUDO_USER }}/.vimrc backup=yes owner={{ chown_owner }} group={{ chown_group }}
  when: overwrite_vim_files == "yes"
