---
- name: Install for new OS
  hosts: local
  sudo: yes
  pre_tasks:
    - apt: update_cache=yes
  roles:
    - vim
    - tmux
    - git
    - system-utilities
    - package-managers
    - {role: shell, shell_type: 'none'}
    - network