- name: netdata
  tags:
    - netdata
  docker:
    name: netdata
    image: titpetric/netdata
    state: started
    net: host
    cap_add: SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Uncomment for active docker container metrics
    ports:
      - 19999:19999
