---
overwrite_bashrc_files: "no"
overwrite_crypto_files: "no"
overwrite_vim_files: "no"

github_alias: "sudohippie"

chown_owner: "{{ ansible_env.SUDO_USER }}"
chown_group: "{{ ansible_env.SUDO_USER }}"
