- name: copy {{ image_name }} Dockerfile
  copy: >
    src={{ image_name }}/Dockerfile
    dest=/tmp/Dockerfile
    force=yes

- name: build {{ image_name }} image
  docker_image: >
    name=sudohippie/{{ image_name }}
    tag=latest
    path=/tmp
    state=present

- name: "{{ image_name }}"
  docker:
    name: "{{ image_name }}"
    image: sudohippie/{{ image_name }}
    state: started