- name: remove old {{ image_name }} Dockerfile
  file: >
    path=/tmp/{{ image_name }}
    state=absent

- name: copy new {{ image_name }} Dockerfile
  copy: >
    src={{ image_name }}
    dest=/tmp

- name: build {{ image_name }} image
  docker_image: >
    name=sudohippie/{{ image_name }}
    tag=latest
    path=/tmp/{{ image_name }}
    state=build

- name: "{{ image_name }}"
  docker:
    name: "{{ image_name }}"
    image: sudohippie/{{ image_name }}
    state: started