---
- name: check if docker is installed
  stat: path=/usr/bin/docker
  register: docker

- name: download docker install script
  when: docker.stat.exists == False
  get_url: url="{{ docker_url }}"
          dest="{{ docker_dest }}"
          validate_certs=no
  register: get_docker

- name: change docker script mode
  when: get_docker|changed
  file: path="{{ docker_dest }}" owner={{ local_user }} group={{ local_group }} mode=a+x

- name: execute docker script
  when: get_docker|changed
  shell: "{{ docker_dest }} > {{ docker_log }}"
