---
- name: install git
  apt: pkg=git state=installed

- name: add .gitconfig
  copy: src=git.gitconfig dest=/home/{{ ansible_env.SUDO_USER }}/.gitconfig backup=yes
  when: overwrite_git_files == "yes"

- name: add .gitignore
  copy: src=git.gitignore dest=/home/{{ ansible_env.SUDO_USER }}/.gitignore backup=yes
  when: overwrite_git_files == "yes"
