---
- name: install git
  apt: pkg=git state=installed

- name: copy .gitconfig
  copy: src=gitconfig dest=/home/{{ ansible_env.SUDO_USER }}/.gitconfig backup=yes
  when: overwrite_git_conf == "yes"

- name: copy .gitignore
  copy: src=gitignore dest=/home/{{ ansible_env.SUDO_USER }}/.gitignore backup=yes
  when: overwrite_git_ignore == "yes"
