- name: mysql container
  tags:
    - mysql
  docker:
    name: mysql
    image: mysql:latest
    state: started
    volumes:
    - "/opt/docker-volumes/mysql:/var/lib/mysql"
    ports:
    - "3306:3306"
    env:
        MYSQL_ROOT_PASSWORD: root